# _config.yml
title: Notepedia

collections:
  notes:
    output: true
    permalink: /notes/:name/

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      type: notes
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post


