#_https://jekyllrb.com/docs/configuration/front-matter-defaults

title: Notepedia

collections:
  notes:
    output: true
    permalink: /notes/:name
  blog:
    output: true
    permalink: /blog/posts/:name

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
  - scope:
      path: ""
      type: blog
    values:
      layout: post

