#_https://jekyllrb.com/docs/configuration/front-matter-defaults

title: Notepedia

collections:
  notes:
    output: true
    permalink: /notes/:title
  blog:
    output: true
    permalink: /posts/:title

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: default
  - scope:
      path: ""
      type: blog
    values:
      layout: default

