const sidebars = {
  homeSidebar: [
    {
      type: 'doc',
      id: 'welcome',
      label: '👋 Welcome'
    },
    {
      type: 'category',
      label: '📜 Cheatsheets',
      items: [
        {
          type: 'category',
          label: 'Hashing & Verification',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/hashing-and-verification'}],
        },
        {
          type: 'category',
          label: 'Help',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/help'}],
        },
        {
          type: 'category',
          label: 'Networking',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/networking'}],
        },
        {
          type: 'category',
          label: 'Package Management',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/package-management'}],
        },
        {
          type: 'category',
          label: 'Remote Desktop Tools',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/remote-desktop-tools'}],
        },
        {
          type: 'category',
          label: 'System Info',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/system-info'}],
        },
        {
          type: 'category',
          label: 'Terminal Pagers',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/terminal-pagers'}],
        },
        {
          type: 'category',
          label: 'Text Manipulation',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/text-manipulation'}],
        },
        {
          type: 'category',
          label: 'User Management',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/user-management'}],
        },
        {
          type: 'category',
          label: 'Web Interaction',
          items: [{type: 'autogenerated', dirName: 'cheatsheets/web-interaction'}],
        },
      ],
    },
    {
      type: 'category',
      label: '📙 Wiki',
      items: [{type: 'autogenerated', dirName: 'wiki'}]
    },
  ],
};

export default sidebars;
