const sidebars = {
  homeSidebar: [
    {
      type: 'doc',
      id: 'welcome',
      label: '👋 Welcome'
    },
    {
      type: 'category',
      label: '📜 Cheatsheets',
      items: [{type: 'autogenerated', dirName: 'cheatsheets'}]
    },
    {
      type: 'category',
      label: '📙 Wiki',
      items: [{type: 'autogenerated', dirName: 'wiki'}]
    },
  ],
};

export default sidebars;
